#!/bin/bash

exec="./d2q9-bgk.llvm"
n=${1:-'128'}
input="input_${n}x${n}.params"
obst="obstacles_${n}x${n}.dat"
cmd="$exec $input $obst"
echo $cmd
mpirun -np 2 \
    --mca btl bxi \
    --mca mpi_common_adge_warning 0 \
    $exec $input $obst
